---
format:
  gfm:
    html-math-method: webtex
jupyter: python3
---

# Summary

This repo takes the [M3](https://www.sciencedirect.com/science/article/abs/pii/S0169207000000571) competition's data and builds 5 different models:

-   Seasonal Naive
-   Auroregressive Integrated Moving Average (ARIMA)
-   Error Trend Seasonality (ETS)
-   Complex Exponential Smoothing (CES)
-   Theta

### Data Exploration

The M3 competition was run in 2000 and contained 3,003 series.

```{python}
#| echo: false
import os
from functools import reduce

import numpy as np
import pandas as pd
from plotnine import (aes, coord_flip, geom_boxplot, geom_col, geom_hline,
                      ggplot, ggsave, labs, scale_y_continuous)
from mizani.formatters import comma_format

def load_data(data_type):
    trainFile = os.path.join(os.getcwd(), f"data/{data_type}_train.csv")

    train = pd.read_csv(trainFile)
    train["ds"] = pd.to_datetime(train["ds"]).dt.normalize()
    train['data'] = data_type
    train = train.sort_values(by=["unique_id", "ds"])

    return train

train_data = map(load_data, ["other", "monthly", "quarterly", "yearly"])
train_data = reduce(lambda x, y: pd.concat([x, y]), train_data)

graph_data = (
    train_data.
    groupby(['data', 'unique_id'], as_index=False).
    agg(
        row_count = ('ds', 'count'),
        avg_value = ('y', 'mean'),
        std_value = ('y', 'std')
    )
)
graph_data["data"] = graph_data["data"].astype("category")
graph_data["data"] = graph_data["data"].cat.reorder_categories(
    ["other", "monthly", "quarterly", "yearly"]
)
```

Long frequency data (i.e. yearly) tend to be shorter series than short frequency series (i.e. monthly). Within each dataset, the length of each series is inconsistent.

```{python}
#| echo: false
(
    ggplot(graph_data, aes(x="data", y="row_count"))
    + geom_boxplot(alpha=0.40)
    + labs(
        x="Data",
        y="Lengths Of Individual Series",
    )
    + scale_y_continuous(labels = comma_format())
    + coord_flip()
)
```

There is large variability in average values of series in all datasets.

```{python}
#| echo: false
(
    ggplot(graph_data, aes(x="data", y="avg_value"))
    + geom_boxplot(alpha=0.40)
    + labs(
        x="Data",
        y="Average Values Of Individual Series",
    )
    + scale_y_continuous(labels = comma_format())
    + coord_flip(ylim=[0, 10000])
)
```

Within each dataset, there is large variability in standard deviations of series. 

```{python}
#| echo: false
(
    ggplot(graph_data, aes(x="data", y="std_value"))
    + geom_boxplot(alpha=0.40)
    + labs(
        x="Data",
        y="Standard Deviations Of Individual Series",
    )
    + scale_y_continuous(labels = comma_format())
    + coord_flip(ylim=[0, 20000])
)
```


# Model Summary

### Comparison with Other Participants 

The seasonal naive model did surprisingly well. However, all 4 statistical models were able to beat it. Error Trend Seasonality is the best model.

```{python}
#| echo: false
fn = os.path.join("data", "metrics_df.csv")
fn = os.path.join(os.getcwd(), fn)
metric_df = pd.read_csv(fn)
metric_df["data"] = metric_df["data"].astype("category")
metric_df["data"] = metric_df["data"].cat.reorder_categories(
    ["other", "monthly", "quarterly", "yearly"]
)
del fn

temp = metric_df.groupby("model", as_index=False)["smape"].mean()
(
    ggplot(temp, aes(x="model", y="smape"))
    + geom_col(alpha=0.40)
    + labs(title="Model Performance", x="Model", y="Average Smape")
    + scale_y_continuous(breaks=np.arange(0, 0.16, 0.02))
    + coord_flip()
)
```


# Code Overview
Run order:

-   prep_data
-   train_stats_models
-   summarize_results

A conda environment file is provided for running the code on Ubuntu.